language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - node_modules
before_script:
  - npm install -g npm@latest
  - npm install -g yarn
  - npm install -g expo-cli
script:
  - yarn
jobs:
  include:
    - stage: deploy website
      script:
        - yarn
        - expo build:web
      deploy:
        provider: netlify
        site: ab7a7225-8523-44cb-aae1-2cd388605775
        auth: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDdH21zuWmSznZrJXLFdkFgtd5iYQftAbAzTTaHKkgyju3VLz2NhbxmELJSjCXX0sO8287u+70weL2J+j1zYFTaM81axVN0VdWjvFJBYdg02zRrAjblVJgadfAnVbuZGAGvOXDA3I5RKpxviorkH9ofayugyHbbrOOV42R3hNqYlKcSTTZ3QbzTPpZIkEEsC3Al2cvXUIB3HHP/j401USY8Aie38li2s3bcdQBP2gAx5bQ0Lp3u8Z6l6nFjPfDpsEPPJReQKXaO3ixGkfnrZcHfCFJ4IWAYmTlVobx7Yulfe1wvi6q4/HxkdOWiC/yErALI1X7/Z7JPxUoW3R5GZA9LB4LVVK/MwTL2Ipr01ab/3INRCe5JUo66V3KkQKxZaWNWTaT9vDq2TDDmGSMC/+ca6coqPLIRsozjnxjqaBMErQjK7Vl83CusEbEngIM0osXiilexrtEyjah2ATr1jb3cyJNgv4UeH6x/8RV20XSKL19TRf+EEWXw+OqNZ5QIbLKaNFA2K/cpvRPr4U73f5kAaV1HjSfxqyZwcCWJuaKk0IEKsAn1EKoJv9o9I1EY56KLVvF9YlJIqJ5uexUdWFp2o454suhzc+vi+uAEA8i03gFEpQpjRt5Y9R0w1QAtkiyCBL4Q5tYfeG4u1TY9pyUlV9q4Y2SbVktRam60OAGNMQ==
        dir: "web-build"
        prod: true
        edge: true
        on:
          branch: master
